### ISSUE TITLE
images.zip missing from dnn-manifest

### ISSUE THREAD

**Issue by tksheppard** [nvisionative/nvQuickTheme#1]
The contents from the images folder isn't included in the manifest.
Adding it to the manifest creates a problem if there are no files within the `[root]/src/images` folder:
`gulp package` doesn't create a zip file if there are no images in the `[root]/src/images` folder. This results in an error when the packaged theme is installing. The manifest is pointing to a zip file that doesn't exist.

**Comment by nvisionative** [comment]
If there is a way to conditionally build *images.zip* based on the existence of any file other than *.gitkeep*, that would be ideal.  Then, of course, it would need to be included in the dnn-manifest if it exists.
