### ISSUE TITLE
RFC: How To Use Symbolic Links for Development Outside of a DNN Instance

### ISSUE THREAD

**Issue by david-poindexter** [nvisionative/nvQuickTheme#101]
## What documentation page needs changing?
New how-to page.

## Proposed documentation change
Add new page to cover how to use Microsoft's built-in Win10 symbolic link feature to develop outside of a DNN instance.  This idea was proposed by @ahoefling, with additional support for PowerShell syntax by @bdukes.  While this seems like a good solution for those wanting to develop outside a DNN instance, this needs more discussion.  There are a few challenges with this as it relates to containers and how the Gulp tasks are currently working.  Please chime in and let's figure out the best approach for this.  It may lead to improvements in the workflow as well.

## Additional context
![image](https://user-images.githubusercontent.com/17751436/38038710-9a92c946-3279-11e8-8bd8-d7c2b2157742.png)

**Powershell Equivalent**
`New-Symlink -LiteralPath SimpleBlog -Target 'D:\Hoefling Software\SimpleBlog'`

[Microsoft Documentation for mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)

**Comment by nvisionative** [comment]
@bdukes @ahoefling @tksheppard - I just ran across [this interesting new feature in Gulp 4](https://gulpjs.com/docs/en/api/symlink).  Check it out and let us know if this is something worth exploring as we work to transition from Gulp 3 to Gulp 4.  Thanks!

**Comment by nvisionative** [comment]
@ahoefling thanks for chiming in.  I remember you saying something about having to reset IIS, but I have yet to experience that issue.  It seems to work well for me.  I have to hard refresh when certain changes are made and caching is involved, but that is true development within the DNN instance as well.

**Comment by OllyHodgson** [comment]
I’ve had the same issue as @ahoefling. JS and CSS changes seem fine, but any server-rendered code (eg .ascx or .cshtml files) need an iisreset.

**Comment by david-poindexter** [comment]
There does not seem to be much interest around this, so we'll go ahead and close this issue out.  Thanks.
