### ISSUE TITLE
Correct stying of search preview list

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#137]
## Describe the bug
If you start to type in the search box, the preview is quite messy.

## To Reproduce
Type something that is used in content in the search box and wait for a sec :-)

## Expected behavior
What I'd prefer:

1. Not show searchSkinObjectPreview_group as it is the name of the module like 'HTML' of 'Content' (2SXC) which is not of help in any of my scenarios.
2. Have the module title above the search result instead of left

**Comment by nvisionative** [comment]
Thanks for reporting this but @Tychodewaard.  We'd like to maintain as much of the core features of the SEARCH skin object as possible, but it could definitely use some styling TLC!  😄

**Comment by Tychodewaard** [comment]
Are you saying it is core related? by default the preview of search results is: 
![image](https://user-images.githubusercontent.com/9091997/53728950-305c6200-3e74-11e9-9c4b-efc3f8d293b0.png)

In Xcillion it looks like:
![image](https://user-images.githubusercontent.com/9091997/53728992-4c600380-3e74-11e9-9e40-ab0d1d8d16bc.png)

**Comment by nvisionative** [comment]
@Tychodewaard thanks for the additional insight.  We'll do an A/B comparison between nvQuickTheme and Xcillion and see if we can tell what is wrong.  I agree that the presentation on Xcillion looks MUCH better and this should be fixed.

**Comment by david-poindexter** [comment]
Good news...I have isolated the issue.  I will discuss solutions with our team and we'll get a fix in for this upcoming 2.1.0 release.

**Comment by david-poindexter** [comment]
Closing per #169
