### ISSUE TITLE
Issue getting colors to update

### ISSUE THREAD

**Issue by Pilot2018** [nvisionative/nvQuickTheme#138]
**nvQuickTheme Video Series - 03 Color Scheme** shows how to update CSS color variables and quickly appt to installed skin by using _gulp watch_  to watch and process changed and saved files. I am unable to get this to work as the changes occur only in these /dist files and not in the those that DNN page points to:

- Downloaded current development environment using zip file option
- Followed installation instructions for additional packages and ran them
- Installed nvQuickTheme skin on DNN 9.02 (Windows 7-64) using nvQuickTheme_2.0.0_install.zip

Steps:
1. Ran gulp watch
2. Open C:\DNN9\Portals\_default\Skins\nvQuickTheme\src\scss\variables\_colors.scss
3. Change $primary-color variable and Save File

gulp watch runs...

C:\DNN9\Portals\_default\Skins\nvQuickTheme>gulp watch
[11:23:51] Using gulpfile C:\DNN9\Portals\_default\Skins\nvQuickTheme\gulpfile.js
[11:23:51] Starting 'watch'...
[11:24:01] Starting 'styles'...
[11:24:03] gulp-notify: [styles] style.min.css compiled and distributed!
[11:24:03] gulp-notify: [styles] style.min.css.map compiled and distributed!
[11:24:03] Finished 'styles' after 1.24 s

4. Go the the open page in DNN w/ nvQuickTheme applied
5. Hard refresh w/ Ctrl-F5
6. No change of colors occurs in DNN page

Check of files shows that:
- C:\DNN9\Portals\_default\Skins\nvQuickTheme\dist\css style files were updated by gulp watch run
- C:\DNN9\Portals\_default\Skins\nvQuickTheme\css style files remain unchanged by gulp watch run
- DNN page source check: href="/dnn9/Portals/_default/skins/nvquicktheme/css/style.min.css?cdv=103"
Only a regeneration of package *.zip and reinstallation will effect the CSS changes.

Please let me know how I can fix this.

**Comment by nvisionative** [comment]
@Pilot2018 thank you for your questions.  It appears you are not developing the theme within a local DNN instance.  Is this correct?  

You don't have to develop within a local instance of DNN, but it is the recommended way.  Please take a look at our detailed [Installation](https://nvisionative.github.io/nvQuickTheme/Installation.html) documentation on how to set up your local development environment.

`gulp watch` will not provide any benefit if you are developing the theme outside of a local DNN instance.  Instead, you would need to make your SCSS changes and then simply run `gulp package` and re-install the theme into your remote DNN instance.

**Comment by Pilot2018** [comment]
I believe I am developing on a local instance of DNN:
- C:\DNN9\ is a locally setup and running DNN  installation.
- C:\DNN9\Portals\_default\Skins\nvQuickTheme\  - is the folder where the my nvQuickView development files reside

I did initially install the theme package zip file with the intent of creating different .ascx layouts
The additional layouts do show and reflect changes to page col/rows made in nvQV on refresh, etc.
It's just colors I can't seem to get to work.

When I change change $primary-color in: 
C:\DNN9\Portals\_default\Skins\nvQuickTheme\src\scss\variables\_colors.scss

gulp watch updates these (2) files:
C:\DNN9\Portals\_default\Skins\nvQuickTheme\dist\css\style.min.css
C:\DNN9\Portals\_default\Skins\nvQuickTheme\dist\css\style.min.css.map

It does not update these files:
C:\DNN9\Portals\_default\Skins\nvQuickTheme\css\style.min.css
C:\DNN9\Portals\_default\Skins\nvQuickTheme\css\style.min.css.map

So my question:  is gulp watch only supposed to update these two files in the nvQuickTheme\dist\css\ folder only or it supposed to update them in the nvQuickTheme\css\ folder as well since this is where source view of DNN pages is looking:
<link href="/dnn9/Portals/_default/skins/nvquicktheme/css/style.min.css?cdv=103" type="text/css" rel="stylesheet"/>

I copied the two pertinent files in the /dist/css/ folder that get updated over-top of those in the  /css/ folder and refreshed my DNN page. All of the colors were updated.

I can use this work-around if this problem is something I created in my experimentation. Thanks for your help and quick response. Great product - really helps development!

**Comment by tksheppard** [comment]
@Pilot2018 There are a few possible things going on here:

1. You have the CRM creating composite files and that is messing up the ability to refresh and see changes without incrementing the version.

2. By installing the theme package on top of the development instance, the theme is now pointing to a different place. When in development, it's setup to point to the 'dist' folder. The output package strips any call to the 'dist' folder and points directly to the associated folders ('css','js','images',etc...). So by installing the install package on top of the instance, the theme is no longer pointing to the dev files, and is instead pointing to the installed package files.

3. This may just be my ignorance, but the locations you posted show:
C:\DNN9\Portals_default\Skins\nvQuickTheme\dist\css\style.min.css
Should be:
C:\DNN9\Portals\_default\Skins\nvQuickTheme\dist\css\style.min.css
With a separation between 'Portals' and '_default'. So it may not be put in the correct place.

The good news is, all of these are fairly simple to fix.
1. Turn off CRM while developing. Or increment the version as necessary.
2. You'll need to replace your 'partials/includes.ascx' file with the original from the nvquicktheme repo. And change any file references to point to the correct location under the 'dist' folder.
3. Change the file structure to be where it should be.

I hope one of these fixes your problem. Let me know how it goes.

**Comment by Pilot2018** [comment]
Thank you for your assistance. Replacing the 'partials/includes.ascx' file with the original did the trick.
The unseparated \Portals_default\ was a typo when creating this request only - was correct in instance  structure.

**Comment by nvisionative** [comment]
@Pilot2018 that is great to hear!
