### ISSUE TITLE
svg files in images folder do not get copied to the dist folder

### ISSUE THREAD

**Issue by valadas** [nvisionative/nvQuickTheme#140]
## Describe the bug
If you put svg images in the src/images folder they do not get copied to the dist folder on build.

## To Reproduce
1. Put some jpeg, gif and svg files in the src/images folder
2. Run gulp build

## Expected behavior
SVG images should get minified according to settings and be output to the dist/images folder

## Errors
Images get copied to the dist folder but not the svg images

**Comment by david-poindexter** [comment]
Closing since #141 was merged into `release/2.0.1`.
