### ISSUE TITLE
Add Support for Razor Templates in DDRMenu

### ISSUE THREAD

**Issue by ahoefling** [nvisionative/nvQuickTheme#142]
## Is your feature request related to a problem?
I personally find it very difficult to use the default menu template engine which is what is currently built into nvQuickTheme. 

https://github.com/nvisionative/nvQuickTheme/blob/master/menus/main/MainMenu.txt

It is complicated for newbies and with Razor Syntax ubiquitous across .NET community I recommend us move to Razor Templating in the DDRMenu. 

## Describe the solution you'd like
Add a new menu template that uses Razor Templating which is supported out of the box by the DDRMenu. Adding a new template preserves the existing `MaintMenu.txt` which allows the theme developer to use the out of the box template they prefer most.

### 2 Templates?
Yes, I think it would be appropriate to maintain 2 menu templates to give the theme developer preference in their favorite template engine. A long term goal I think we should have is create an additional command to the CLI interface to quickly swap between templates. (not part of this issue thought)

## Describe alternatives you've considered
This recommendation makes the theme dev experience better.

**Comment by nvisionative** [comment]
@ahoefling thank you for bringing this idea to **nvQuickTheme** - it is something that more people need to know about and we agree this is the right way to go about it!

**Comment by david-poindexter** [comment]
Closing since #144  was merged into `release/2.0.1`.
