### ISSUE TITLE
Updating bootstrap and font awesome

### ISSUE THREAD

**Issue by dougcsicam** [nvisionative/nvQuickTheme#143]
## Please summarize your question in one sentence
Whay would be the correct procedure to upgrade Bootstrap and Font Awesome to the latest version within this framework.

**Comment by nvisionative** [comment]
@dougcsicam which version of **nvQuickTheme** are you using?  If you are version 2.0.0 then all you need to do is run the appropriate `yarn upgrade bootstrap` or `yarn upgrade font-awesome` command(s).  You can also modify the versions in **package.json** and re-run `yarn` or `yarn install`, though that is not the recommended best practice.

**Comment by dougcsicam** [comment]
I was able to upgrade bootstrap but not fontawesome. I used 
yarn upgrade font-awesome@5.8.1
This is what it returns
Couldn't find any versions for "font-awesome" that matches "5.8.1"
? Please choose a version of "font-awesome" from this list:
> 4.7.0
  4.6.3
  4.6.1
  4.5.0

**Comment by nvisionative** [comment]
The package names for Font Awesome 5 changed.  Try `@fortawesome/fontawesome-free`

**Comment by nvisionative** [comment]
You need to uninstally Font Aesome 4 and install Font Awesome 5.

**Comment by dougcsicam** [comment]
I upgated to fontawesome 5  after iuninstalling 4 with the command:
yarn add --dev @fortawesome/fontawesome-free
When I do the build I get the error:
'faCssInit' errored after 9.21 ms
[10:34:00] Error: File not found with singular glob: C:/inetpub/wwwroot/dnndev/Portals/_default/Skins/SicamQtTheme/node_modules/font-awesome/css/font-awesome.min.css (if this was purposeful, use `allowEmpty` option)

**Comment by nvisionative** [comment]
@dougcsicam when using Font Awesome 5, that will create a new folder within **node_modules** for **@fortawesome/fontawesome-free**.  Therefore, `gulpfile.js` will need to be updated to accommodate the new Font Awesome location.  [THIS LINE](https://github.com/nvisionative/nvQuickTheme/blob/master/gulpfile.js#L35) change would need to be updated to match the location of the minified CSS file.

**Comment by david-poindexter** [comment]
Issues #156 and #157 have been added to address this in nvQuickTheme and has been added to Milestone 2.1.0.  Closing this issue as a result.
