### ISSUE TITLE
Use default styling

### ISSUE THREAD

**Issue by mathisjay** [nvisionative/nvQuickTheme#146]
I realize you may have purposefully altered to the styling to show how it can be done.  However, the default color choices are not intuitive.   For example, the color red has a contextual meaning of danger/warning/bad , so to have red as the default color for btn-primary is not a good choice.

I suggest making the defaults actually be the BS4 defaults as this is most likely what people are expecting.  Otherwise, it takes the "quick" out of "nvQuickTheme" when the developer has to go in and set everything back the default color scheme.

**Comment by nvisionative** [comment]
@mathisjay **nvQuickTheme** is a theme building tool.  The colors in the out-of-the-box theme are based on the DNN brand colors and can easily be changed.  See [more details about making color changes](https://nvisionative.github.io/nvQuickTheme/Change-Color-Scheme.html) here.  Thanks.
