### ISSUE TITLE
Customized Bootstrap Components

### ISSUE THREAD

**Issue by kingjordan** [nvisionative/nvQuickTheme#15]
Hello,

How do you see people adding custom components for bootstrap.  For example,  If I created three different versions of a "pricing table".  Let's say I only want it on the services page and I want the second of the three bootstrap price table I created.  Could we have a folder for community provided elements that you could select and then the gulp/yarn packaging could pull in the needed sass, js, html for the selected component?

Just wanting to start a conversation about this.  I provide a lot of "simple" sites with elements that I use across a lot of sites that just need color changes or minor tweaks.  I would love the ability to build out the components, add them to the skin and then have the main sass colors etc customize respectively.

I hope this makes sense :)

**Comment by nvisionative** [comment]
@kingjordan Thanks for the post.  This sounds like a solution based on your specific use case and not something that we would roll into nvQuickTheme directly.  It sounds like you may need to just use nvQuickTheme as a "starter solution" and build out your own unique workflow to incorporate these custom components.
