### ISSUE TITLE
_header.scss styles not being used

### ISSUE THREAD

**Issue by jncraig** [nvisionative/nvQuickTheme#151]
## Describe the bug

I've added some styles to _header.scss. That file does not seem to be loading, and the styles are not making it to style.min.css.

_footer.scss has no issues.

## To Reproduce
1. Add some styles to _header.scss
2. let the project rebuild
3. load the site
4. styles aded to _header.scss do not seem to be included, and are not seen in style.min.css

## Expected behavior
Styles would be included.

## Errors
Paste the error(s) related to this issue.

**Comment by nvisionative** [comment]
@jncraig have you modified the `_sections.scss` file?  If not, it should build just fine.  Just make sure `_sections.scss` has the `@import 'header';` line still there.

**Comment by jncraig** [comment]
As usual ...  ID10T!

**Comment by nvisionative** [comment]
No worries @jncraig - what was the issue?

**Comment by jncraig** [comment]
It really was me.  Not counting the laws of quantum mechanics, you really can't be in two places simultaneously.  In my case, I was making changes in one place and expecting them to be seen in another.

**Comment by nvisionative** [comment]
@jncraig ah okay - glad you figured it out!  Have a great day.
