### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by jncraig** [nvisionative/nvQuickTheme#152]
## Please summarize your question in one sentence

Help editing scss files when developing

## Give a more extended description
As I am developing a theme, when I edit a scss file, should I be doing the editing in the css folder, or in src/css?  When I edit in src/css, it looks like gulp notices this and rebuilds, but the files are not updated in the /css directory.  So, I don't see the changes in the website.  If I package and reinstall, all is ok.

But, is this the right way to be doing things.  (I'm pretty sure that I should not be editing directly in /css, right?)

**Comment by nvisionative** [comment]
@jncraig all styling edits should be done in` src/scss` (there is no `src/css` folder).  

The Gulp build process (e.g. `gulp build`, `gulp package` or `gulp watch`) handles compilation of all SCSS files and outputs the appropriate minified CSS.  You should never touch any output CSS files directly.  Let the build process handle that for you.

**Comment by Pilot2018** [comment]
This closed issue may or may not help:
Issue getting colors to update #138

**Comment by jncraig** [comment]
Yes.  I means scss ...

I'm seeing gulp build kicking in, but the files in css/ don't seem to be
updated.

**Comment by nvisionative** [comment]
@jncraig can you be more specific?

1. What exact steps are you performing?  
2. What is the result?  
3. What is your expected result?

**Comment by tksheppard** [comment]
@jncraig

It sounds like you've installed your theme package over top of your development environment. At this point, you will need to replace your `includes.ascx` with the original from nvquicktheme, as well as delete the `css`, `js`, `fonts`, and `images` folders if they are appearing in the root of your project. `gulp build` compiles the scss into `dist/css`.

**Comment by david-poindexter** [comment]
Closing this issue due to no response.  Feel free to re-open if help is still needed.
