### ISSUE TITLE
Add 'TARGET' token to support DNN open page in new window

### ISSUE THREAD

**Issue by JoeAiken** [nvisionative/nvQuickTheme#164]
## Is your feature request related to a problem?
**Please describe.**
When going to Content > Pages > setting Page Type to 'URL' and turning on the 'Open Link in New Window' toggle, the functionality does not work

## Describe the solution you'd like
Add the proper menu token ([=TARGET]) to MainMenu.txt and RazorMenu.cshtml files. 

## Describe alternatives you've considered
N/A

## Additional context
Within theme of clients website I had added the 'target="[=TARGET]"' to all <a> tags within the MainMenu.txt and this restored the proper functionality

**Comment by david-poindexter** [comment]
Closing per #170
