### ISSUE TITLE
Add complete clean rebuild of the dist folder on build/package

### ISSUE THREAD

**Issue by tksheppard** [nvisionative/nvQuickTheme#176]
## Is your feature request related to a problem?
The dist folder is currently just overwritten upon build or package. I suggest that the dist folder be removed and rebuilt completely as to prevent old files from sticking around and causing problems. The dist folder should not contain any files that aren't being generated through the build and package tasks.

## Describe the solution you'd like
During the build and package tasks, there should be a task that deletes the old dist folder before rebuilding. This task should also function as a stand-alone command.

**Comment by david-poindexter** [comment]
Closing per #181 - thanks @piotrchmielinski!
