### ISSUE TITLE
Add optional 'hidden' LOGIN theme object

### ISSUE THREAD

**Issue by tksheppard** [nvisionative/nvQuickTheme#177]
## Is your feature request related to a problem?
When working on a site that doesn't have an accessible DNN LOGIN theme object, it is annoying to have to navigate to the login page.

## Describe the solution you'd like
I suggest a small transparent box in the bottom left or bottom right that will popup the DNN Login controls.

**Comment by david-poindexter** [comment]
Closing per #182
