### ISSUE TITLE
Build or package throws error

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#178]
## Describe the bug
After gulp build or package it says:
events.js:183
      throw er; // Unhandled 'error' event
      ^
CssSyntaxError: C:\NVquicksites\tjepstest01\Website\Portals\_default\Skins\Boomhwd\src\scss\style.css.min.map:1:32: Missed semicolon>
followed by a whole lot of characters

## To Reproduce
NVQuicktheme 2.1.0
Install yarn (1.7.0)
Install gulp (CLI version: 2.2.0 / Local version: 3.9.1)
Update npm
Create package

At first it says:
[11:07:19] Starting 'manifest'...
[11:07:19] Finished 'manifest' after 3.24 ms
[11:07:19] gulp-imagemin: Minified 0 images
[11:07:19] Finished 'images' after 68 ms
[11:07:19] gulp-notify: [containers] Containers updated!
[11:07:19] gulp-notify: [manifest] Manifest updated successfully!
But then the error

## Expected behavior
Package without errors

**Comment by david-poindexter** [comment]
@Tychodewaard thanks for creating this issue.  We have yet to experience any of this.  First off, there should be no `src\scss\style.css.min.map` file.  All minified CSS and corresponding MAP files should be in the `\dist\css` folder.

Also, we highly recommend using only **yarn** and not **npm** for package management.

**Comment by Tychodewaard** [comment]
In the video on https://www.youtube.com/watch?v=KIJrfndGMzE you can see that I can accomplish the same with just installing gulp and yarn

**Comment by david-poindexter** [comment]
@Tychodewaard thanks for the video.  There appear to be several issues at play here.  

1.  The theme code base you show in the video does not match what we have on GitHub.  Please make sure you always start fresh by cloning or downloading the repo ZIP from the GitHub `master` branch.  

2.  It appears you have some **Gulp 3** vs **Gulp 4** issues going on.  Please see #155 for some helpful tips on getting this sorted out.

3.  We really need to update our documentation accordingly.  Our apologies for the confusion here.  I will create an issue now for this.

**Comment by Tychodewaard** [comment]
This issue has been solved in https://github.com/nvisionative/nvQuickTheme/issues/155
