### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#179]
## Describe the bug
When building / packaging there are some errors. They don't sound serious and I can see my theme and changes locally (scss is built). 
But when I install the package, the theme (called quicktjeps) is the theme is available twice (global and site 1 of the with layout and container, the other without. The one without container throws an  error: Could Not Load Theme: /Portals/0-System/skins/quicktjeps.ascx, Error: The file '/Portals/0-System/skins/quicktjeps.ascx' does not exist.

## To Reproduce
Build or package the NVQuicktheme

## Expected behavior
No errors

What happens during building is: (I included the lines just before the errors).
[13:11:01] Starting 'normalizeInit'...

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist

--------------
[13:11:01] Starting 'styles'...

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist

------------------

**Comment by david-poindexter** [comment]
@Tychodewaard it seems you are using an older version of **nvQuickTheme**.  Please make sure you are using the latest version (2.1.0).  This error does not exist using v2.1.0.  We'll go ahead and close this issue, but feel free to re-open if you think it is still valid.  Thanks.
