### ISSUE TITLE
css files

### ISSUE THREAD

**Issue by jncraig** [nvisionative/nvQuickTheme#180]
## Please summarize your question in one sentence

Where is the right place to put some miscellaneous css files?

**Comment by david-poindexter** [comment]
@jncraig could you be a bit more specific?  **nvQuickTheme** follows a suggested file/folder structure under `src/scss' for all SCSS files (e.g., `variables`, `sections`, `components`).  No CSS files should be used within, but CSS can be placed within any SCSS existing or new file and it should compile to CSS just fine.

**Comment by jncraig** [comment]
If I add a new scss file in the scss folder, do I need to do anything else to get it included in the compilation?

**Comment by david-poindexter** [comment]
Yes, let's say you want to add a new SCSS file for a subheader within `src/scss/sections`.  

1. Create a new SCSS file called `_subheader.scss` within that folder.  

2. Modify `_sections.scss` to import that new SCSS file by adding a line for the following:

    `@import 'subheader';`

Let us know if this is what you need.

**Comment by jncraig** [comment]
And if I want to add a /src/scss/extras folder, what would I do?

**Comment by jncraig** [comment]
Ah, got it!

**Comment by david-poindexter** [comment]
The recommended approach for new folders is to follow the model already established.  Every SCSS folder contains a file called `_foldername.scss` that handles importing sibling SCSS files within that folder.  So in your case, you would create a file called `_extras.scss` within `src/scss/extras` to handle imports.  Then you would add the other SCSS files accordingly to that folder.  Lastly, you would need to update `src/styles.scss` to `@import 'extras/extras'`.

**Comment by david-poindexter** [comment]
@jncraig we are going to go ahead and close this issue, but feel free to re-open if you still need clarification on anything.
