### ISSUE TITLE
How to structure git files for multiple pages

### ISSUE THREAD

**Issue by worldheadquarters** [nvisionative/nvQuickTheme#183]
## Please summarize your question in one sentence
How can the repository files be structured/changed so that the build process creates more than one layout file?

## Give a more extended description
Theme sets often have multiple layouts within the theme group.  Example: one for admin, one without the login/user widget. As the current project is structured, it produces only one layout.  I would like to know how to create more than one layout within the build as well as more than one container.  This whole process with github, npm, yarn, scss etc. is new to me. I don;t totally understand it.

**Comment by tksheppard** [comment]
@worldheadquarters 

nvquicktheme is already setup to handle any number of layouts and containers. All you need to do is add whatever layouts you want in the root of the folder (the same place as the default.ascx). In similar fashion, any other containers you make in the `containers` folder will be accounted for as well.

The build process doesn't actually touch the layout files, and all it does with containers is make sure they are put in the correct folder for your development instance. The package process accounts for all `.ascx` files within the root of the projects, as well as containers. And the manifest is setup to handle any containers that are included. So no customization necessary! Build out your layouts and containers, and let nvquicktheme handle the rest!
