### ISSUE TITLE
Yarn dependancy errors

### ISSUE THREAD

**Issue by worldheadquarters** [nvisionative/nvQuickTheme#184]
## Please summarize your question in one sentence
What should I do about Yarn dependency errors?

## Give a more extended description
When running yarn in  git bash, I get the following errors/messages:
-----
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
-----
## Steps to reproduce (if needed)
clonel nvquicktheme to portals/_default/skins
change name of folder
edit project-details.json appropriately
in git bash, change to appropriate directory
run yarn

## Other comments or remarks
I'm not sure what to do abut this or if it is even important

**Comment by david-poindexter** [comment]
@worldheadquarters long story short, those are fine and can be ignored.  I’m going to go ahead and close this issue, but feel free to reply if you run into any issues.
