### ISSUE TITLE
Rename all.min.css to 'fontAwesome.min.css'

### ISSUE THREAD

**Issue by mathisjay** [nvisionative/nvQuickTheme#193]
The FontAwesome CSS library is being compiled into a bundle called "all.min.css". This is misleading and should be renamed to be descriptive of what it is.

**Comment by david-poindexter** [comment]
@mathisjay that is the official name of the FontAwesome CSS.  We wouldn’t want to change that, as people that know FontAwesome will then be more confused.  Plus, we are not compiling it - just copying it from package to output.

**Comment by mathisjay** [comment]
If someone want to link another font library that also happens to name their output "all.min.css", what would be the right course of action?

**Comment by david-poindexter** [comment]
That would be up to that specific implementation.  One approach would be to simply place each package in their own subfolder.
