### ISSUE TITLE
h* colour definition?

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickTheme#200]
## Please summarize your question in one sentence
I am trying the find the place where the h* colour styling can be defined

## Give a more extended description
I want to give h1, h2 etc a different colour than the base body colour

## Steps to reproduce (if needed)
I cannot find the place where to define that

**Comment by EPTamminga** [comment]
Question placed on slack.

**Comment by david-poindexter** [comment]
Headings are defined [here](https://github.com/nvisionative/nvQuickTheme/blob/master/src/scss/_base.scss) and you could add colors there using Bootstrap or custom variables for the desired colors.
