### ISSUE TITLE
nvquicksite.com needs app pool recycled!

### ISSUE THREAD

**Issue by VashJuan** [nvisionative/nvQuickTheme#201]
## Describe the bug
Nvquicksite.com is down.

## Screenshots
![Screenshot_20200406-022805_Firefox](https://user-images.githubusercontent.com/8594671/78544261-b735e980-77ae-11ea-9418-80022348b0b4.jpg)

## Errors

Service Unavailable

HTTP Error 503. The service is unavailable.

## Additional
![Screenshot_20200406-022805_Firefox](https://user-images.githubusercontent.com/8594671/78543989-53abbc00-77ae-11ea-9c46-58b4e4cb3f43.jpg)

**Comment by VashJuan** [comment]
NvQuicktheme.com too

**Comment by david-poindexter** [comment]
@VashJuan thank you.  nvquicktheme.com is back online.  nvquicksite.com will be most likely on Monday.  We are rebuilding that site, but the information is still on GitHub and the GitHub Wiki for nvQuickSite.
