### ISSUE TITLE
PopUpSkin.ascx load error in ready-to-go install pack and source code

### ISSUE THREAD

**Issue by janbeumer** [nvisionative/nvQuickTheme#220]
The new PopUpSkin.ascx is causing a load error:
Skin /Portals/_default/skins/nvQuickTheme/popUpSkin.ascx, could not be loaded. Error: Unknown serverlabel dnn:DnnCssInclude.

## To Reproduce
1. Clean install DNN 9.6.1 (or 9.6) using nvquicksite, site language Dutch.
2. Install nvQuickTheme 2.2.0
3. Set site default to default.ascx
4. Open module settings, for example an HTML module
5. Abovementioned error will appear

## Expected behavior
PopUpSkin.ascx will load correctly, without errors.

## Screenshots
![image](https://user-images.githubusercontent.com/19649385/81917287-4a93e300-95d5-11ea-9998-6ed207c63fb9.png)

## Errors
Skin /Portals/_default/skins/nvQuickTheme/popUpSkin.ascx, could not be loaded. Error: Unknown serverlabel dnn:DnnCssInclude.

## Additional context
new since addition of popupskin.

**Comment by JoeAucoin** [comment]
Add this to _registers-popUpSkin.ascx

`<%@ Register TagPrefix="dnn" Namespace="DotNetNuke.Web.Client.ClientResourceManagement" Assembly="DotNetNuke.Web.Client" %>`

**Comment by david-poindexter** [comment]
Thanks for letting us know about this.  We'll get it slated for the next release.

**Comment by david-poindexter** [comment]
Closing this issue per #233 - the fix will be included in Version 2.2.1.
