### ISSUE TITLE
Yarn Install Warnings

### ISSUE THREAD

**Issue by LynJoyce** [nvisionative/nvQuickTheme#224]
## Please summarize your question in one sentence
Upon running Yarn, the following warning appeared.
 How do I fix the dependency warnings please?

## Give a more extended description
I installed Yarn v1.22.4  using Git Bash which ran which informed me of the following:
info  fsevents@1.2.12L The Platform Win 32 is incompatible with this module
Warning of two unmet dependencies
warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9 -3"
warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0"
## Steps to reproduce (if needed)
Clone nvQuickTheme to instance running on Windows 10 64-bit
Run Yarn install

## Other comments or remarks
Are these dependencies essential to ensure that everything runs smoothly? 
![yarn-warning](https://user-images.githubusercontent.com/66784899/85959472-b1f2d000-b994-11ea-84c6-7c8a9c0f0c7f.png)

**Comment by david-poindexter** [comment]
@LynJoyce thank you for the questions.  

1. jQuery is loaded by DNN, not the theme.  So you can ignore that warning.
2. popper.js is loaded as a part of the bootstrap bundle, so that dependency warning can also be ignored.

Thanks!

**Comment by LynJoyce** [comment]
Thank you David for your quick response and reassurance, much appreciated.

Warm regards

**Comment by david-poindexter** [comment]
You are most welcome @LynJoyce - have a great and safe week!
