### ISSUE TITLE
GitHub Actions for CI

### ISSUE THREAD

**Issue by SkyeHoefling** [nvisionative/nvQuickTheme#228]
## Please summarize your question in one sentence
I recently setup a new theme project using GitHub for my repository and went with Actions instead of using Azure Pipelines which is my normal build engine. I was curious if the nvQuickTheme team is interested in seeing a Pull Request to convert the existing build to Actions?

## Give a more extended description
N/A

## Steps to reproduce (if needed)
N/A

## Other comments or remarks
N/A

**Comment by david-poindexter** [comment]
That would be great @ahoefling - that has been on my TODO list, but I just haven't gotten around to it yet.  😉   Any help is most appreciated!
