### ISSUE TITLE
Is Gulp Serve Working? 

### ISSUE THREAD

**Issue by skrantzman** [nvisionative/nvQuickTheme#231]
## Please summarize your question in one sentence
Did you manage to get the gulp serve/browser sync feature working correctly?

## Give a more extended description
I am running my dnn theming environment through a subdomain "theme.dnndev.me".  The site opens and displays correctly when viewing that address directly. 

![Normal](https://user-images.githubusercontent.com/7874652/89443305-f6485d00-d704-11ea-8b07-8afa9845724e.JPG)

 If I changed the proxy domain in gulpfile.js to match, and then run gulp serve, the site opens in a new browser tab as it should, but the persona bar is missing, and there are some other various glitches.

![proxy](https://user-images.githubusercontent.com/7874652/89443335-ff392e80-d704-11ea-8f6e-fc19319e111a.JPG)

## Other comments or remarks
One a side note, I added the following to the gulpfile, to include changes to ascx files as well:

Added a path for dnn ascx files
```
	dnn: {
		src: "./**/*.ascx",
	},
```
Modified the serve() function to include
```
        gulp.watch(paths.dnn.src).on("change", bs.reload);
```
These changes allow live browser syncing for changes to the dnn theme files which is useful for side by side development.

**Comment by david-poindexter** [comment]
@skrantzman yes, browsersync has been working since June 2019 and we have not experienced any of this behavior.  Perhaps something else in your instance or project is causing this?
