### ISSUE TITLE
Broken Image Source Links In Documentation

### ISSUE THREAD

**Issue by skrantzman** [nvisionative/nvQuickTheme#232]
## What documentation page needs changing?
All pages of [nvQuickTheme](https://nvisionative.github.io/nvQuickTheme/) documentation.

## What documentation section needs changing?
Image src links are broken in all sections.

![broken_links_1](https://user-images.githubusercontent.com/7874652/89666157-b7461300-d88e-11ea-95c6-4f4f340addcb.JPG)

This is also an issue with [nvQuickSite's wiki pages](https://github.com/nvisionative/nvQuickSite/wiki) as well.

## Proposed documentation change
Fix src links

## Additional Side Note
Also on a side note the double arrow and x icons of the popup login screen on the nvQuicktheme.com site are missing. See the upper right corner of the login screen below:

![broken_links_2](https://user-images.githubusercontent.com/7874652/89666594-7ac6e700-d88f-11ea-9d96-291a1766cba3.JPG)

These icons appear correctly on my local installs of nvQuickTheme, and just appear to be an issue with the nvQuickTheme.com site.

**Comment by david-poindexter** [comment]
@skrantzman thanks - most of these have now been resolved.  We need to completely redo the screenshots for nvQuickSite to match the current version, so it is on our TODO list.  ;-)
