### ISSUE TITLE
DDR Menus using Token templates have lots of empty Target attribute tags

### ISSUE THREAD

**Issue by jeremy-farrance** [nvisionative/nvQuickTheme#243]
## Describe the bug
![image](https://user-images.githubusercontent.com/653301/96943571-2ef30980-149e-11eb-8725-8573467755a7.png)
 
## To Reproduce
1. If not already that way, configure the theme to use the DDR Menu Token templates.

## Expected behavior
We shouldn't see empty target attributes in the <a> tags.

## Screenshots
Included above.

## Additional context
DNN Dave is the greatest.

**Comment by david-poindexter** [comment]
Thank you @jeremy-farrance - looking forward to the PR! 🎉🎉🎉
