### ISSUE TITLE
Missing Split Border When Disable Page is On

### ISSUE THREAD

**Issue by skrantzman** [nvisionative/nvQuickTheme#246]
## Describe the bug
If a page that has children, has Disabled Page set to On, then in the collapsed menu the split does not show a border around it (See Volunteer Page split below in the first screenshot).  In the expanded menu, the split appears to be missing the white left border (See Volunteer Page split below in the second screenshot).

## Screenshots
Collapse Menu
![image](https://user-images.githubusercontent.com/7874652/100135376-660e5f00-2e3e-11eb-8566-ffaaf516c4a0.png)

Main Menu
![image](https://user-images.githubusercontent.com/7874652/100136143-7c68ea80-2e3f-11eb-84a5-640e11ae9638.png)

## To Reproduce
1. Create a parent page (level 1) with sub pages (level 2)
2. View the page split on the main menu
3. Resize browser until collapse menu appears
4. The split button associated with the parent page has a border.
5. Now set the Disable Page feature to On for the parent page.
6. The split button associated with the parent page no longer has a border.
7. Maximize the Browser to view the full main menu
8. The split for the parent page is missing the left white border.

## Expected behavior
I expect to see a border around the split button whether or not the parent page has Disable Page set to On or Off.

**Comment by tksheppard** [comment]
@skrantzman 
This behavior is intended. If the parent page is disabled, it doesn't require a direct link. This is signified visually by combining into a single button. If you wish to change this, you'll need to go into either your menu template, or the SCSS and make the necessary changes.
