### ISSUE TITLE
Footer Hidden Login

### ISSUE THREAD

**Issue by LynJoyce** [nvisionative/nvQuickTheme#249]
## Please summarize your question in one sentence
How do I enable the hidden <dnn:Login runat="server" id="dnnHiddenLogin" CssClass="hiddenLogin" /> login located in partials/footer.ascx?

## Give a more extended description
I want to move the user login to the site footer.
Currrently the footer contains a hidden login link<dnn:Login runat="server" id="dnnHiddenLogin" CssClass="hiddenLogin" /> which I would like to enable without breaking the site.

## Steps to reproduce (if needed)
Removed the User controls from the header.
Edited <dnn:Login runat="server" id="dnnHiddenLogin" CssClass="hiddenLogin" />
to <dnn:Login runat="server" id="dnnLogin" CssClass="Login" />
The result broke the site.
I enclosed it in a container but it broke the site. I used the CSS Class = user-controls the result broke the site.

## Other comments or remarks

Please advise how do I enable the footer login without breaking anything?

**Comment by tksheppard** [comment]
@LynJoyce 
Thanks for using nvquicktheme!

The hidden login is already activated. It is a small transparent square in the bottom left of the website that allows you to get to the login.

If you want to add another login to the footer you'll have to add another login object with a unique id.

**Comment by tksheppard** [comment]
In 2.2.1 you'll need to go to `_login.scss` and under `.hiddenlogin` change `display:none` to `display:block`.

I am planning on changing this to be enabled by default in the future.
