### ISSUE TITLE
Remove incorrect wiki about installation package

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickTheme#25]
This isn't true: https://github.com/nvisionative/nvQuickTheme/wiki/Download-and-Install-the-Out-Of-Box-Theme

**Comment by nvisionative** [comment]
Thanks @iJungleboy - we have updated the wiki [HERE](https://github.com/nvisionative/nvQuickTheme/wiki/Working-With-the-Out-Of-Box-Theme).
