### ISSUE TITLE
Add sourcemaps to allow for more effective development

### ISSUE THREAD

**Issue by nvisionative** [nvisionative/nvQuickTheme#27]
Currently, using browser dev tools references minitfied CSS files (which is not very helpful during development).  We need to add sourcemaps so dev tools will reference source SCSS files.

**Comment by john-Graham** [comment]
Here's how I changed my gulp.task... 

Added

sourcemaps    = require('gulp-sourcemaps'),

and

`gulp.task('scss', function() {
  return gulp.src( './'+src+'scss/**/*.scss')
  .pipe(sourcemaps.init())
    .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
    .pipe(sourcemaps.write())
    .pipe(rename({suffix: '.min'}))
    .pipe(autoprefixer({browsers: ['last 2 versions', 'ie >= 9', '> 1%']}))
		.pipe(gulp.dest( './'+dist+'/css/'))
		.pipe(notify({message: 'Styles compiled successfully!', title : 'sass', sound: false}));
});`

**Comment by nvisionative** [comment]
@john-Graham thank you!  Would you be interested in making a pull request for this enhancement?

**Comment by john-Graham** [comment]
@nvisionative sure.  Just tried.

**Comment by nvisionative** [comment]
Thanks @john-Graham.  Unfortunately, we see no [new pull requests](https://github.com/nvisionative/nvQuickTheme/pulls).  :)

**Comment by nvisionative** [comment]
@tksheppard it looks like you closed this issue, but there is no associated pull request.  Perhaps this was part of the _snafu_ we discussed?  If so, no worries.  For those finding this issue after-the-fact, we have added this functionality to the master branch.  If you are looking for this feature, please update your local repo to include.  Thanks!
