### ISSUE TITLE
gulp build fails with latest node version

### ISSUE THREAD

**Issue by weggetor** [nvisionative/nvQuickTheme#28]
Got always errors when trying to run "gulp anything". Tried to install / uninstall yarn, gulp etc.
At the end it was the node version! After installing v8.12.2 (LTS) everything works fine. Maybe add a note to the Wiki ?

**Comment by bdukes** [comment]
The long-term solution here is to upgrade to Gulp v4, but a note should probably also be added, for now.  FYI, Yarn 1.7.0 is the first version to support Node.js 10, also.

**Comment by nvisionative** [comment]
Thank you for reporting this @weggetor.  And thanks for the assist here @bdukes (would you mind creating an issue for the Gulp v4 upgrade so we can get this on the roadmap)?  For now, we have updated [Wiki - Installation](https://github.com/nvisionative/nvQuickTheme/wiki/Installation) to notate our recommendation to use the latest LTS version.
