### ISSUE TITLE
Change the default DNN Button appearance

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickTheme#286]
## Is your feature request related to a problem?
Not a problem, but an enhancement. The standard DNN buttons are a bit old fashioned, especially if you compare that with the PB buttons.

## Describe the solution you'd like
Change the SCSS for the DNN Buttons in the default nvQuickTheme default code

## Describe alternatives you've considered
Define my own buttons in my modules, but that would mean that the buttons of the default DNN modules would remain old fashioned and different.

## Additional context

**Comment by EPTamminga** [comment]
An example is the HTML/text module, text editing or settings: legacy style DNN buttons. I have changed the button scss in the DNN.scss, so any legacy DNN button automagically changes to a more contemporary design. 
Yes, custom modules can do their own design, but than there will be an inconsistency between custom module and standard DNN modules?

**Comment by david-poindexter** [comment]
@EPTamminga if you have already done this in `_dnn.scss` are you planning to submit a PR?

The reason we haven't done this in nvQuickTheme is that it is kind of a mixing of concerns.  There is no "right way" to implement this within the theme.  This theme uses Bootstrap.  DNN does not.  So, to pull this off in a consistent manner, you would essentially have to "reinvent the wheel" and duplicate Bootstrap styling but just for the various DNN specific button styles.  😉

**Comment by EPTamminga** [comment]
Yes, I planned to submit a PR.

However, I am not an experienced css/scss developer, so I can use some feedback on the changes.

In addition: I would like to add some extra color variables (or use existing ones if they are defined for that purpose), so that the button definitions do not have coded colors, but have colors that are defined as variables in the _color.scss

**Comment by david-poindexter** [comment]
Closing per #290
