### ISSUE TITLE
Names and purpose of the colors

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickTheme#288]
## Please summarize your question in one sentence
Is there an explanation which color variables are used fir what purpose?

## Give a more extended description
The color variables have names. Which is intended for what?

## Other comments or remarks

**Comment by david-poindexter** [comment]
This version of nvQuickTheme uses Bootstrap 4, so color variables are consistent with it.  They can be modified via proper extending of the framework variables via `/src/scss/variables/_bs-overrides.scss`.  

In addition to the standard Bootstrap color variables, we have custom ones defined in `/src/scss/variables/_colors.scss`.  These can be used however you like.

There are also SCSS mixins for various button styles here: https://github.com/nvisionative/nvQuickTheme/blob/develop/src/scss/mixins/_mixins.scss#L35-L88

I hope this helps.

**Comment by EPTamminga** [comment]
@david-poindexter I will try to make some additional documentation in the _colors.scss.

That said. I really like the effort you have put into nvQuickTheme, it enables a none-skinner (like me) to create a well-behaved DNN theme...

**Comment by EPTamminga** [comment]
In the instruction video about colors in nvQuickTheme the color names in _colors.scss where:

![image](https://user-images.githubusercontent.com/5859855/154693479-db2492ad-1b23-4f95-816f-11ca7eabe1cf.png)

Now, the color names in _colors.scss are:
```
colors: (
    "white":white,
    "light-shade":#e6e6e6,
    "light-accent":#e0e1eb,
    "main-shade":#ec3d46,
    "main-accent":#462a2b,
    "main-highlight":#00a5e1,
    "sub-shade":#005a7b,
    "sub-accent":#00a5e1,
    "sub-highlight":#48ceff,
    "dark-shade":#050621,
    "dark-highlight":#484858,
    "black":black
);

```
How do the new color names releate to primary, secundary & tertiary color?

**Comment by EPTamminga** [comment]
I understand that the colors are custom, but can I make a relation between de original color names in _colors.scss as explained & shown in the NVQT instruction video (color names that are easy to understand), and the names as they are currently in _colors.scss?

So what are the primary, secondary and tertiary colors in the current list of color names in _colors.scss? 
Or is there no relationship anymore, because of the colors in the current _colors.scss just additional free names for colors to be used anywhere in the theme?

**Comment by david-poindexter** [comment]
@EPTamminga apologies for the confusion, but we abandoned the relationship between the custom color scheme and Bootstrap's primary, secondary naming convention because it was confusing.  So, there is no relationship between them anymore.
