### ISSUE TITLE
Using symbolic links to shadow dist folder into the DNN Skin folder

### ISSUE THREAD

**Issue by weggetor** [nvisionative/nvQuickTheme#29]
Would be a good idea to use symbolic links to "shadow" the dist folder of the skin project into the DNN skin folder. Otherwise these files needed to be copied after each build to test the changes!

**Comment by nvisionative** [comment]
Great question @weggetor!  Most people use **mklink** to shadow the entire nvQuickTheme clone directory during development.  Combing that with the **_gulp watch command_** makes for a nice workflow - just refresh page and see the latest theme file changes in action.  For those that do not know about **mklink**, [SEE HERE](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink).  Another helpful link is [HERE](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/).
