### ISSUE TITLE
Include koi.json file in the built package

### ISSUE THREAD

**Issue by yog-it** [nvisionative/nvQuickTheme#291]
## Is your feature request related to a problem?
When installing a module that utilizes koi connect, a theme installed in an instance of DNN from the package built does not broadcast its framework.

## Describe the solution you'd like
I believe including the koi.json file in the theme package would resolve the issue.

## Describe alternatives you've considered
Manually copying the koi.json file into the instance's theme directory works.  

## Additional context
Your project rocks, by the way.  More devs need in on this awesomeness. Thank you for making this a public project.

**Comment by david-poindexter** [comment]
@yog-it thanks so much for the kind words.  Are you saying there may be a packaging issue with the inclusion of `koi.json`?  If so, then this may be a simple fix in `gulpfile.json`.

**Comment by yog-it** [comment]
Yes.  If I just clone the project, run `yarn` and then `gulp package`, the built package doesn't include the `koi.json`.  

I changed this
```
zipelse: {
    src: ['./menus/**/*', './partials/*', '*.{ascx,xml,html,htm}'],
    zipfile: 'else.zip',
    dest: './temp/'
  },

```
To this and it worked like a charm
```
zipelse: {
    src: ['./menus/**/*', './partials/*', '*.{ascx,xml,html,htm}','koi.json'],
    zipfile: 'else.zip',
    dest: './temp/'
  },
```

Is that the proper way to add single files to the package?

**Comment by david-poindexter** [comment]
@yog-it that's exactly how to do it!  Would you like to submit a pull request for this?  We would certainly accept it.  :)
