### ISSUE TITLE
Support multiple custom theme projects within nvQuickTheme dev environment

### ISSUE THREAD

**Issue by tksheppard** [nvisionative/nvQuickTheme#3]
Possible to setup the dev environment somewhere else and have it modify/watch specific projects?

- Would further declutter the actual theme folder while in dev.
- Would allow for separately updating dev environment and theme projects.
- Would allow for separate gits of nvQuickTheme environment and nvQuickTheme dev theme.
- nvQuickTheme dev theme would be dependent upon nvQuickTheme environment.

**Comment by nvisionative** [comment]
Based on our in-house dialogue about this, let's instead move towards a multi-project setup.  In this approach, the tooling would be placed one directory up (`~\Portals\_default\skins` if developing with DNN instance).  That way, the base nvQuickTheme theme would be in a sub-folder named *nvQuickTheme*.  Additional theme projects could then be added via more sub-folders under *skins*.

This approach would obviously require some modifications to the existing tooling, but would all theme developers to keep up to date with the latest and greatest nvQuickTheme tooling without having to rework existing custom theme back into our repo.
