### ISSUE TITLE
Upgrade to Gulp 4.x

### ISSUE THREAD

**Issue by bdukes** [nvisionative/nvQuickTheme#30]
Gulp 3.x is not compatible with Node.js 10, causing the issues documented in #28.  Ultimately, the Gulp process should be upgraded to use version 4 of Gulp.

### Some resources:

- [`npm install gulp@next` talk](https://github.com/phated/talks/blob/master/npm-install-gulp-at-next/slides.pdf) from Gulp's primary maintainer
- [Official Getting Started documentation](https://github.com/gulpjs/gulp/pull/2182)
- [Gulp 4 interview](https://medium.com/gulpjs/gulp4-interview-with-blaine-bublitz-d94bfaa7dc78)
- [Slides](https://slides.com/briandukes/using-gulp-to-create-a-front-end-build-pipeline) and [code](https://github.com/bdukes/using-gulp-to-create-a-front-end-build-pipeline) from my DNN Summit presentation which compared 3.x to 4.x.

**Comment by nvisionative** [comment]
@bdukes a pull request (#124) has been submitted and merged into the [version/2.0.0 branch](https://github.com/nvisionative/nvQuickTheme/tree/version/2.0.0).  This is the branch where we are staging all v2.0.0 code until we are ready for the official release.  We are closing this issue to help keep things organized will in the [2.0.0 milestone](https://github.com/nvisionative/nvQuickTheme/milestone/1).  Let us know if you have any questions or concerns with the implementation.  Thanks again for posting this issue and bringing the issue to light.
