### ISSUE TITLE
Colors video out of date

### ISSUE THREAD

**Issue by profK** [nvisionative/nvQuickTheme#345]
## Please summarize your question in one sentence
The color video refers to "primary, secondary and tertiary' colors but these do not exist in _colors.scss

## Give a more extended description
The file in the video looks like this:
![image](https://user-images.githubusercontent.com/4048613/214095625-ea6bc97e-73a3-40d2-a69d-9dd4c0cb374e.png)

But the actual file looks like this:
![image](https://user-images.githubusercontent.com/4048613/214095789-b4945956-ef4d-466c-8dd8-bc58ee236540.png)

**Comment by david-poindexter** [comment]
@profK thanks for pointing this out.  We do need to update several areas of the documentation.  Everything was correct at the time of creation, but much has changed with nvQuickTheme since then.  😉  We'll try to get some time carved out to update our documentation.

**Comment by david-poindexter** [comment]
This will be changing drastically in v4.0.0 (which will move towards supporting DNN 10).  Therefore, we are going to close this issue.
