### ISSUE TITLE
Built packages don't consistently overwrite if output filename is the same as existing packages

### ISSUE THREAD

**Issue by tksheppard** [nvisionative/nvQuickTheme#348]
## Describe the bug
When a theme package is built, it doesn't consistently overwrite existing packages of the same version. This may be specific to packageStyles, but can easily be fixed by making sure all output packages are forced to overwrite.

## To Reproduce
1. Run packageSyles command
2. Make styling updates
3. Run packageStyles command
4. Compare output build file to what the output file is in `dist`

## Expected behavior
Overwite existing build packages of the same version (same name)

**Comment by david-poindexter** [comment]
Great catch @tksheppard 🎉

**Comment by david-poindexter** [comment]
@tksheppard I am just now getting a chance to look into this and am confused.  There is no `packageStyles` gulp task.  Are you referring to the `styles` task?  If so, are you saying the CSS in the dist folder is not being overwritten?

**Comment by tksheppard** [comment]
Looks like this was a bug when we were creating multiple install packages on an older version of nvQuickTheme. We have since removed that functionality, so it isn't an issue.
