### ISSUE TITLE
Updates to the nvQuickTheme Video Series - 02 Project Setup

### ISSUE THREAD

**Issue by INNO-Software** [nvisionative/nvQuickTheme#353]
## What documentation page needs changing?
[[The YouTube video here: https://www.youtube.com/watch?v=7UhpbUaeFQc](https://youtu.be/7UhpbUaeFQc?t=1165)](https://youtu.be/7UhpbUaeFQc?t=1165)
Titled: nvQuickTheme Video Series - 02 Project Setup

## What documentation section needs changing?
At the timestamp in the YouTube link (above) you reference 'gulp package' which is no longer a valid task in the latest version of nvQuickTheme.

## Proposed documentation change
I recognize it can be tricky to 'fix the video', but we might noting that this gulp task was replaced with 'gulp packageTheme' in the latest version of nvQuickTheme. Some people might be stumped by this if they are new to gulp.

## Describe alternatives you've considered
Perhaps a note at the top of the YouTube video description or directly next to the 'Project Setup' video links on the documentation site: https://nvisionative.github.io/nvQuickTheme/Project-Setup.html -and- https://nvisionative.github.io/nvQuickTheme/

**Comment by david-poindexter** [comment]
This will be changing drastically in v4.0.0 (which will move towards supporting DNN 10).  Therefore, we are going to close this issue.
