### ISSUE TITLE
Update koi.json to use bs5

### ISSUE THREAD

**Issue by ropalko** [nvisionative/nvQuickTheme#365]
## Describe the bug
The current [koi.json](https://github.com/nvisionative/nvQuickTheme/blob/e74992ab8d03b81a1fb5a8d98608582a1777e449/koi.json) files uses bs4 instead of bs5. When working with Koi, the framework assumes that "BS4" is used even though it is a BS5 skin.

## Expected behavior
Skin should be labeled as BS5 Skin

**Comment by david-poindexter** [comment]
Great catch!
