### ISSUE TITLE
Location to edit classes

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#39]
When I add a module to the full width pane, it is actually not full width.
I guess the fact that somewhere it is defined as justify-content-center, is causing this.
Question 1: where is that stated? Where do I state that pane or a module should be using justify-content-center? Or better: what is the correct place to edit this?
Question 2: where can I add / edit classes?  So, if I like to change container-fluid or add another container

**Comment by tksheppard** [comment]
Hi and thanks for your question,

The "Full Width" pane is actually labeled as "FullWidthBGDoublePaneOne[Two]" The Background on these panes are full-width, not the actual content pane. I can see why this caused confusion.

The answer to both your questions, I believe, is in the default.ascx file. Any definitions of Bootstrap classes for Panes and surrounding containers are defined here. For the section you're looking at, it looks like:

```html
  <div class="container-fluid bg-tertiary">
    <div class="container">
      <div class="row align-items-center">
        <div id="FullWidthBGDoublePaneOne" class="col-md-6 cpy-5" runat="server"></div>
        <div id="FullWidthBGDoublePaneTwo" class="col-md-6" runat="server"></div>
      </div>
    </div>
  </div>
```

A lot of these classes are being inserted here via Bootstrap 4 classes. I recommend reading up on Boostrap 4 documentation [here](https://getbootstrap.com/docs/4.1/getting-started/introduction/) if you need help with anything Boostrap.

If that isn't your question, and you are asking how to add/edit classes into the css, please read about the SCSS setup for nvquicktheme [here](https://github.com/nvisionative/nvQuickTheme/wiki/SCSS).

**Comment by Tychodewaard** [comment]
Many thanks, this helped a lot!

**Comment by nvisionative** [comment]
You are welcome @Tychodewaard - thanks @tksheppard
