### ISSUE TITLE
Wiki Update: Recommend Yarn installer

### ISSUE THREAD

**Issue by bdukes** [nvisionative/nvQuickTheme#4]
Yarn doesn't recommend installing via npm, see "Install via npm" on https://yarnpkg.com/en/docs/install#alternatives-tab, so the [Installation page](https://github.com/nvisionative/nvQuickTheme/wiki/Installation#install-yarn) should probably just point to https://yarnpkg.com/en/docs/install

**Comment by nvisionative** [comment]
Thank you for the tip @bdukes - we have updated the installation instructions accordingly and will go ahead and close this issue.
