### ISSUE TITLE
vertical alignment language object

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#40]
## Please summarize your question in one sentence
How can I vertically align flag icons for multi language to baseline? 

## Give a more extended description
I'm trying to use NVQuicktheme for a multi-language site. I'm using the flag icons but the alignment is not ok. The vertical alignment needs to be baseline. I think there is a margin on the selected language but I can not figure out where this is set

## Steps to reproduce (if needed)
Activate a second language.

## Other comments or remarks
I figured I add
`.language-object {
    vertical-align: baseline
}`
to src - scss - components - _dnn.scss but that doesn't do the trick. Any suggestions where/how to fix this?

**Comment by nvisionative** [comment]
@Tychodewaard great question!  We will have to test this one out and circle back to you.  We have a pretty heavy workload right now, but will get back to you as soon as possible.  In the meantime, let us know if you come across a solution.

**Comment by Tychodewaard** [comment]
Thanks to sourcemapping, I was able to detect this myself. 

In my case, I have 2 languages active, so maybe in a scenario with 3 or more languages you still want the default settings. 

Long story short: to have 2 language flags vertically aligned, you remove the lines 28 and 44 (display:inline-flex) in the file _nav.scss
