### ISSUE TITLE
Discover true css

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#41]
## Please summarize your question in one sentence
Do you have a pointer to discover the true css behind the minified css?

## Give a more extended description
Before Sass, it was really easy to verify in developer tools what css rule is responsible for the styling. Now, when I want to change/fix things, I only see the minified file which is not helping. Do you have a way to find the 'true css'?

**Comment by nvisionative** [comment]
@Tychodewaard - yes, please see issue #27 for details.  You should update your local repo and you'll have the new sourcemaps feature.
