### ISSUE TITLE
gulp build Error missing semicolon

### ISSUE THREAD

**Issue by websystemsoftware** [nvisionative/nvQuickTheme#42]
Hi,
always when i build the project with gulp build i become the following error:

events.js:183
      throw er; // Unhandled 'error' event
      ^
CssSyntaxError: D:\Projekte\Demo\Portals\_default\Skins\TestTheme1\src\scss\style.css.min.map:1:32: Missed semicolon>

i download from github..
they are all original files from github and i make no changes....

what is the problem does the project not can build
and brings always this error?

thanks
benny

**Comment by nvisionative** [comment]
@websystemsoftware thank you for reporting this.  We will look into it.

@tksheppard does this have something to do with the addition of sourcemaps?

**Comment by Tychodewaard** [comment]
I can confirm that this happens to me to with the new version. So, it's not an incident.

**Comment by nvisionative** [comment]
Thanks @websystemsoftware for reporting this.  And thanks @Tychodewaard for confirming the issue.  A PR has been submitted and merged to the master branch.  Give it a spin and let us know how it goes!

**Comment by websystemsoftware** [comment]
Hi,
now works perfect without errors....

Thanks
Benny

**Comment by nvisionative** [comment]
Thanks for letting us know!
