### ISSUE TITLE
Background scale sub sub level

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#45]
## Describe the bug
Sub sub navigation not scaling

## To Reproduce
Create a long page name for the sub sub level.

## Expected behavior
The background should scale along with the content,.

## Additional context
By default in the _nav.scss on line 206 it says: `width: 100%;`
If you repace that with `white-space: nowrap;` the issue is solved.

(i tried to create a pull request but somehow that failed, must be something in my system)

**Comment by nvisionative** [comment]
Thanks for reporting this @Tychodewaard
