### ISSUE TITLE
Update .gitignore to ignore dist folder

### ISSUE THREAD

**Issue by john-Graham** [nvisionative/nvQuickTheme#47]
## Please summarize your question in one sentence
I'm curious mostly the .gitignore is excluding 

- dist/css/style.min.css
- dist/css/bootstrap.min.css

shouldn't we just as well ignore the whole folder?

dist/

**Comment by jordanpinski** [comment]
The /dist folder contains more than those two files.

**Comment by nvisionative** [comment]
This has sparked a nice healthy internal conversation here and we believe some re-architecture is warranted.  Currently only the required files are in the /dist folder out-of-the-box.  Mainly these are files supporting Bootstrap and Font Awesome.  We discussed and agreed these file should actually be in a source folder somewhere (TBD) and we'll rely on the gulp build process to place them appropriately in the /dist folder.  Once that is completed, we can absolutely ignore the entire /dist folder via **.gitignore**.  Thanks for indirectly bringing this to light!

**Comment by john-Graham** [comment]
Excellent.  That'd be great. I ended up dumping BS4 and switched it to CSS Grid, and upgraded to FA5 and added that to part in the _includes and referenced the CDN.

<dnn:DnnCssInclude ID="DnnCssIncludeFontAwesome" runat="server" FilePath="https://use.fontawesome.com/releases/v5.0.13/css/all.css" Priority="110" />

it let me delete the whole folder and watch it get recreated.  :-)

**Comment by nvisionative** [comment]
@john-Graham while it is outside the scope of this thread, we really don't recommend using the Client Dependency Framework (CDF) in DNN to load from a CDN.  It technically works, but it does unfortunate have a side-effect of performance issues.  Our recommendation is to pull your FA files local and let them be loaded from your server.  Hopefully in the future, there will be enhancements made to the CDF in DNN to correct the performance issues.

Regarding Font Awesome 5, we would welcome any insight you have gained there.  Let's create another issue so we can have some threaded conversation about that.  Would you mind creating that issue so you can be easily mentioned in the thread?

Thanks!
