### ISSUE TITLE
Missing images paths inside .scss files like _dnn.scss

### ISSUE THREAD

**Issue by flurdulis** [nvisionative/nvQuickTheme#48]
I was moving your package from gulp to webpack 4. When I started processing .scss files, I basically got stuck, because files are not found example is "InstallWizardBG.png". 

.dnnWizardStepArrow {
    width: 25px;
    height: 46px;
    background: transparent url(../../../../../../images/InstallWizardBG.png) no-repeat;
    background-position: 0 -401px;
}

I am new to DNN, and not sure whether these images come from the Portal folder once you install the package under dnndev.me, or they are simply errors. Please advise. If these images come from DNN portal, then it will be hard to compile in webpack outside of the dnn environment. I am trying to work in standalone mode, before installing the package into dnndev.me site. 

Please advise.

Thank you!
Ella

**Comment by flurdulis** [comment]
I did find the images, they are under dnndev.me/images path. For webpack, compilation of things outside of the root folder is a tricky path. It won't compile. My question is, how important these images are? Can I move them into the package, for example, and have nvquicktheme be standalone for dev purposes without having to depend on dnndev.me/images? I prefer standalone theme package without those references. I counted 33 images being referenced. I want to move away from the idea of images dependence. Please advise.

Thanks!
Ella

**Comment by nvisionative** [comment]
@flurdulis with DNN themes, it is considered best practice to style some common elements built-in to DNN and those rely on images built-in to DNN (*~/images* folder).  Those are the ones you are seeing.  It would not be advisable to move those to within the theme package, but rather find a workaround for the Sass compilation.

If you do get it all working with Webpack 4, would you be willing to write up a blog about your experience and why you chose to go this route?  That could bring a lot of value to those that prefer to use Webpack within the DNN Community.  I'm sure we could get you blogger rights on dnnsoftware.com.

**Comment by tksheppard** [comment]
We will be leaving the linking to the original DNN icons for now. Hopefully this eventually becomes a non-issue as DNN completely severs the tie of it's CSS from the CSS of the theme.
