### ISSUE TITLE
Please create nvQuickTheme_<version>_Install.zip for download for each release

### ISSUE THREAD

**Issue by jeffmparker** [nvisionative/nvQuickTheme#54]
Hi, for those of us who just want to use the nvQuickTheme as an extension for a DNN site, i.e. not as a base to create a custom theme as a developer, would you be able please to create the installation zip file for download as outlined on https://nvisionative.github.io/nvQuickTheme/Working-With-the-Out-Of-Box-Theme.html for each release?

**Comment by nvisionative** [comment]
@jeffmparker thank you for posting this request.  We initially did just that - we provided the theme install package for each release.  We honestly don't mind doing this again, but we discovered it was causing quite a bit of confusion before.  nvQuickTheme is a framework and workflow for DNN theme development.  It was never intended to be used as _just another free theme_, though we certainly don't mind that.  The problem and confusion comes in when people download that theme install package, install it into their DNN instance and then try to customize it after-the-fact.  That will only lead to frustration and again, it never was our intent to start with.  Theme customization should happen prior to packaging it up and installing.  That said, we will either update the documentation to no longer mention these packages or we will provide the install packages for each release.

**Comment by nvisionative** [comment]
@jeffmparker the base out-of-the-box theme install package has now been added to the two official releases tagged [v1.0.0](https://github.com/nvisionative/nvQuickTheme/releases/tag/v1.0.0) and [v1.1.0](https://github.com/nvisionative/nvQuickTheme/releases/tag/v1.1.0).  Thanks!
