### ISSUE TITLE
Upgrade to Font Awesome 5

### ISSUE THREAD

**Issue by john-Graham** [nvisionative/nvQuickTheme#55]
## Is your feature request related to a problem?
Not related to any problems.

## Describe the solution you'd like
Look into upgrading to Font Awesome latest version. (Currently 5.1) rather than use 4. 

## Describe alternatives you've considered
No alternatives considered this is more to keep up-to-date with the use of the more recent version of Font Awesome

**Comment by john-Graham** [comment]
Throwing this in here and shooting it down right away.   I'm noticing that in FA 5,

FA-arrows, and fa-pencil are both for pro only.   Thus in edit mode there are missing icons when in the edit mode on hover.   

![screen shot 2018-07-16 at 11 02 53 am](https://user-images.githubusercontent.com/7405524/42769522-f70cf33a-88e7-11e8-9e4d-840718d31928.png)

**Comment by nvisionative** [comment]
@john-Graham thanks for looking into this - that's a bummer!  We will go ahead and close this issue.

**Comment by horacioj** [comment]
I think there is a solution.

pencil-alt is free.  https://fontawesome.com/icons?d=gallery&q=pencil&m=free
There are arrows too

To make it compatible with 4.x, even using 5.0, and valid for DNN menu options, add this:

```
            ClientResourceManager.RegisterScript(Page,
                VirtualPathUtility.AppendTrailingSlash(TemplateSourceDirectory) + "lib/font-awesome/js/fa-v4-shims.min.js"
                , FileOrder.Js.DefaultPriority + ++scriptPriority);`
```
