### ISSUE TITLE
Switch from gulp-autoprefixer to autoprefixer and add process to gulpfile.js

### ISSUE THREAD

**Issue by john-Graham** [nvisionative/nvQuickTheme#56]
## Is your feature request related to a problem?
Yes, but not directly affecting this implementation.   I'm using css grid and missing a bunch of autoprefixed css that may fix some of the CSS grid issues. 

## Describe the solution you'd like
gulp-autoprefixer is listed as a required NPM Module (https://www.npmjs.com/package/gulp-autoprefixer) But I'm not sure this is even being used,  I don't see it being called in the gulp process.

I'm thinking two fold approach, switch from gulp-autoprefixer to autoprefixer https://www.npmjs.com/package/autoprefixer) Autoprefixer seems to be a much more active module. Then call the autoprefixer in the gulp process.  Documentation on gulp implementation is on the autoprefixer page.   

## Describe alternatives you've considered
Haven't done a deep dive into alternatives.   Other suggestions? 

edit:fixed wording

**Comment by john-Graham** [comment]
Not sure how / why I missed it but I do see pipe.autoprefixer in the gulpfile, so I'll be looking a bit deeper to see why some of my expected prefixes are missing.

**Comment by tksheppard** [comment]
Hey John,

That's awesome you've been using CSS Grid effectively! I've used it several times and loved it, although I haven't been thrilled with the lack of support. Checking at [ttp://sass-lang.com/documentation/file.SASS_REFERENCE.html](ttp://sass-lang.com/documentation/file.SASS_REFERENCE.html) it shows an unfortunate 87.7% support rate.

As for suggestions, the only prefix that currently increases support rate from what I can see is the -ms- prefix. The prefix is only partially supported and accounts for 2.7% of usage. If you're okay with using css-grid with 87% support rate, does the 2.7% make that much of a difference?

If the difference provided by replacing gulp-autoprefixer with autoprefixer would help get the support rate for css-grid up to acceptable levels, I would definitely make it a priority to change it. But until css-grid becomes more widely supported and gets the kinks worked out, I'm not inclined to make the change. However, I'm still not against it. From what I can see, like you said, autoprefixer seems to be much more active, so it's probably the better option anyway. If you worked out the switch in a PR, we would definitely shift it over.
