### ISSUE TITLE
Version Number Stored in Multiple Manifest Files

### ISSUE THREAD

**Issue by ahoefling** [nvisionative/nvQuickTheme#62]
## Describe the bug
The version is stored in a total of 3 files and becomes confusing if you want to automated semantic versioning with npm commands.

+ DNN Manifest File (this can be ignored since the gulp `manifest` task overwrites it)
+ project-details.json
+ package.json

## To Reproduce
1. Clone a new project
2. run the command `npm version patch`

## Expected behavior
The version number in package.json is incremented as expected. BUT the version number in project-details.json is not incremented. 

## Additional context
I would argue that the version number should be used from the package.json file and not the project-details.json. Or they should be kept in sync when the user uses the `npm version` command.

**Comment by ahoefling** [comment]
I submitted a PR for what I changed locally in my theme development. I don't know if you can accept it because I changed where the version number lives, but I wanted to provide the code change

**Comment by nvisionative** [comment]
@ahoefling one thing you may not know is our plans to support multiple theme packages within nvQuickTheme.  See #3 for more details.  In that regard, the version in **package.json** should match the version of nvQuickTheme and the the version in **project-details.json** should match the version of the individual theme.  Make sense?  Thanks.

We will update the version number in **package.json** to match the correct version of nvQuickTheme.  We'll create a separate issue to address that specific issue.

**Comment by ahoefling** [comment]
Thanks for the clarification on this issue.

**Comment by nvisionative** [comment]
@ahoefling you are most welcome - thanks for helping us to make this a better solution for everyone!
