### ISSUE TITLE
Unable to update Bootstrap version

### ISSUE THREAD

**Issue by sholman** [nvisionative/nvQuickTheme#66]
## Describe the bug
Updating the dependency version in the package.json file then running yarn does not update the referenced bootstrap version

Normalise.css is also included in the packages.json but is not added to the dist/css folder. This is not as much of an issue as it's not referenced in the includes.ascx

## To Reproduce
1. extract nvQuickTheme zip to folder
2. Update Bootstrap version in package.json from 4.0.0. to ^4.1.0
3. run yarn
4. package in node_modules is updated to 4.1.x but the scss files in the assets folder, which the gulp build tasks uses, is not updated.

**Comment by nvisionative** [comment]
@sholman we agree this area definitely needs some attention.  Our apologies for the delayed response.  We have not been able to give as much attention to these things over the past few months.  Thanks for taking the time to document this.
