### ISSUE TITLE
missing src reference in the gulpfile.js

### ISSUE THREAD

**Issue by sholman** [nvisionative/nvQuickTheme#67]
## Describe the bug
The images task in the gulpfile.js uses the following reference ('./images/**/*.{jpg,jpeg,png,gif}') which is inconsistent with the convention of storing source files in the src folder. Any images placed in the src/images folder will be ignored during the build process

This should be updated to ('./'+src+'images/**/*.{jpg,jpeg,png,gif}') to reference the src folder

**Comment by nvisionative** [comment]
@sholman thank you for reporting this.  We will look into it as soon as possible and circle back to you.  

As far as pull requests go, you would need to create a branch in your repo for each issues you would like submit a PR for.  That way, only the relevant changes are included.  We follow a model of branch names like `issue-##`.  This keeps things nice and clean.

**Comment by nvisionative** [comment]
@tksheppard this does appear to be a bug.  Can you confirm?

**Comment by tksheppard** [comment]
Indeed it is a bug. It's a leftover relic from one of the original iterations. Nice catch @sholman!
