### ISSUE TITLE
Add support for theme Release Notes in manifest and package

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#68]
## Please summarize your question in one sentence
Where do I put the release notes?

## Give a more extended description
During install there is an area for release notes. How can I utilize this within NVQuickTheme?

**Comment by nvisionative** [comment]
@Tychodewaard if you want to include a **ReleaseNotes.txt** file in your package, then you could look into updating the [zipelse gulp task](https://github.com/nvisionative/nvQuickTheme/blob/master/gulpfile.js#L198-L204) to include **txt** files.  Then you'd need to update the [manifest gulp task](https://github.com/nvisionative/nvQuickTheme/blob/master/gulpfile.js#L160-L175) to include the following:
`<releaseNotes src="ReleaseNotes.txt"></releaseNotes>`

@tksheppard this is probably something we should look into including out-of-box as it is a standard in DNN theme and module development.

**Comment by nvisionative** [comment]
@Tychodewaard a pull request (#119) has been submitted and merged into the [version/2.0.0 branch](https://github.com/nvisionative/nvQuickTheme/tree/version/2.0.0).  This is the branch where we are staging all v2.0.0 code until we are ready for the official release.  We are closing this issue to help keep things organized will in the [2.0.0 milestone](https://github.com/nvisionative/nvQuickTheme/milestone/1).  Let us know if you have any questions or concerns with the implementation.  Thanks again for posting this issue and bring the issue to light.

FYI...we will also be creating an issue and subsequent pull request to add proper support for the theme license.  Right now it is leveraging the nvQuickTheme LICENSE file, but that is obviously not acceptable for everyone and that is mixing the nvQuickTheme licensing with the custom theme (output) license.  These are two different things and should be handled separately.
