### ISSUE TITLE
Action menu button styling isn't quite right for SPA modules with QuickSettings

### ISSUE THREAD

**Issue by OllyHodgson** [nvisionative/nvQuickTheme#72]
## Describe the bug
The styling for the action menu buttons does not apply to the QuickSettings button on an SPA module.

## To Reproduce
1. Edit a page
2. Hover over an SPA module with QuickSettings

## Expected behavior
All the buttons look the same.

## Screenshots
![image](https://user-images.githubusercontent.com/437224/47795830-16224400-dd1b-11e8-965c-a0c5e1275612.png)

## Additional context
I have a PR incoming to fix this.

**Comment by nvisionative** [comment]
Great catch @OllyHodgson!
